ARG AIRFLOW_VERSION=${AIRFLOW_VERSION}
ARG PYTHON_VERSION=${PYTHON_VERSION}
ARG AIRFLOW_IMAGE_TAG=${AIRFLOW_VERSION}-python${PYTHON_VERSION}
FROM apache/airflow:$AIRFLOW_IMAGE_TAG
ARG AIRFLOW_VERSION
WORKDIR /opt/airflow
ADD requirements.txt .
RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt